### ISSUE TITLE
error since yesterday.

### ISSUE THREAD

**Issue by N0NameN0** [TimLChan/fbchat#4]
Anything change at FB side ? 

Traceback (most recent call last):
  File "./sendFB.py", line 37, in <module>
    session = fbchat.Session.login("XXXXXXX", "XXXXXXXX")
  File "/usr/local/lib/python3.5/dist-packages/fbchat/_session.py", line 377, in login
    return cls._from_session(session=session)
  File "/usr/local/lib/python3.5/dist-packages/fbchat/_session.py", line 434, in _from_session
    define = parse_server_js_define(r.content.decode("utf-8"))
  File "/usr/local/lib/python3.5/dist-packages/fbchat/_session.py", line 36, in parse_server_js_define
    raise _exception.ParseError("Could not find any ServerJSDefine", data=html)
fbchat.ParseError: Could not find any ServerJSDefine. Please report this, along with the data below!

**Comment by N0NameN0** [comment]
work again ;)
